// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyExpenseTracker.Repository.Database;

#nullable disable

namespace MyExpenseTracker.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyExpenseTracker.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acrynonym")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acrynonym = "SBI",
                            Name = "State Bank of India",
                            Type = "National"
                        },
                        new
                        {
                            Id = 2,
                            Acrynonym = "HDFC",
                            Name = "HDFC Bank",
                            Type = "National"
                        },
                        new
                        {
                            Id = 3,
                            Acrynonym = "ICICI",
                            Name = "ICICI Bank",
                            Type = "National"
                        },
                        new
                        {
                            Id = 4,
                            Acrynonym = "AXIS",
                            Name = "Axis Bank",
                            Type = "National"
                        },
                        new
                        {
                            Id = 5,
                            Acrynonym = "BOB",
                            Name = "Bank of Baroda",
                            Type = "National"
                        },
                        new
                        {
                            Id = 6,
                            Acrynonym = "BOI",
                            Name = "Bank of India",
                            Type = "National"
                        },
                        new
                        {
                            Id = 7,
                            Acrynonym = "CBI",
                            Name = "Central Bank of India",
                            Type = "National"
                        },
                        new
                        {
                            Id = 8,
                            Acrynonym = "PNB",
                            Name = "Punjab National Bank",
                            Type = "National"
                        },
                        new
                        {
                            Id = 9,
                            Acrynonym = "UBI",
                            Name = "Union Bank of India",
                            Type = "National"
                        },
                        new
                        {
                            Id = 10,
                            Acrynonym = "KOTAK",
                            Name = "Kotak Mahindra Bank Ltd.",
                            Type = "National"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
